server:
  port: 8761

spring:
  application:
    name: eureka-server
  # Micrometer tracing / Zipkin Properties
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

management:
  tracing:
    sampling:
      probability: 1.0

# Eureka Properties
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
    prefer-ip-address: true
