server.port=${PORT:10000}

eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443
eureka.instance.non-secure-port-enabled=false
eureka.instance.home-page-url=https://${RENDER_EXTERNAL_HOSTNAME:localhost}/
eureka.instance.status-page-url=https://${RENDER_EXTERNAL_HOSTNAME:localhost}/actuator/info
eureka.instance.health-check-url=https://${RENDER_EXTERNAL_HOSTNAME:localhost}/actuator/health
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://eureka:password@localhost:8761/eureka}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.cloud.gateway.server.webflux.routes[20].uri=${EUREKA_SERVER_URL:https://cinesaga-eureka-server.onrender.com}
spring.cloud.gateway.server.webflux.routes[21].uri=${EUREKA_SERVER_URL:https://cinesaga-eureka-server.onrender.com}
