server.port=8080
spring.mongodb.uri=mongodb://mongodb:27017/cinesaga
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0
eureka.client.serviceUrl.defaultZone=http://eureka:password@eureka-server:8761/eureka
app.mail.sender=${APP_MAIL_SENDER:no-reply@cinesaga.local}
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.protocol=${MAIL_PROTOCOL:smtp}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.kafka.bootstrap-servers=kafka:29092
