server.port=8080
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:cine_saga}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:12345}
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0
eureka.client.serviceUrl.defaultZone=http://eureka:password@eureka-server:8761/eureka
app.mail.sender=${APP_MAIL_SENDER:no-reply@cinesaga.local}
#spring.kafka.bootstrap-servers=kafka:29092
