server.port=8080
spring.data.mongodb.uri=mongodb://mongodb:27017/cinesaga
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0
eureka.client.serviceUrl.defaultZone=http://eureka:password@eureka-server:8761/eureka
app.mail.sender=${APP_MAIL_SENDER:no-reply@cinesaga.local}
#spring.kafka.bootstrap-servers=kafka:29092
